apiVersion: v1
kind: Service
metadata:
  name: badge-admin-service
  namespace: badge-system
  labels:
    app.kubernetes.io/name: badge-admin-service
    app.kubernetes.io/part-of: badge-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: badge-admin-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
