apiVersion: v1
kind: Service
metadata:
  name: badge-management-service
  namespace: badge-system
  labels:
    app.kubernetes.io/name: badge-management-service
    app.kubernetes.io/part-of: badge-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: badge-management-service
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
